'use client'

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react'
import { format as formatDateFn } from 'date-fns'

type Language = 'en' | 'bn'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  formatNumber: (num: number) => string
  formatCurrency: (amount: number) => string
  formatDate: (date: Date, format?: string) => string
}

// Bengali number conversion
const englishToBengaliNumbers = (num: string): string => {
  const bengaliDigits = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯']
  return num.replace(/[0-9]/g, (digit) => bengaliDigits[parseInt(digit)])
}

// Bengali month names
const bengaliMonths = [
  'জানুয়ারী', 'ফেব্রুয়ারী', 'মার্চ', 'এপ্রিল', 'মে', 'জুন',
  'জুলাই', 'আগস্ট', 'সেপ্টেম্বর', 'অক্টোবর', 'নভেম্বর', 'ডিসেম্বর'
]

const translations = {
  en: {
    // Login Form
    'login.title': 'Welcome back',
    'login.subtitle': 'Sign in to your DocLedger account',
    'login.phone': 'Phone Number',
    'login.phonePlaceholder': '01XXXXXXXXX',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.signingIn': 'Signing in...',
    'login.signIn': 'Sign In',
    'login.needHelp': 'Need help? Contact',
    'login.allRightsReserved': 'All rights reserved',
    
    // Login Page
    'login.brandTitle': 'DocLedger',
    'login.brandSubtitle': 'Streamline your document workflow',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to Dashboard',
    'dashboard.logout': 'Logout',
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Welcome to your DocLedger dashboard',
    'dashboard.documents': 'Documents',
    'dashboard.documentsDesc': 'Manage your documents here',
    'dashboard.reports': 'Reports',
    'dashboard.reportsDesc': 'View and generate reports',
    'dashboard.settings': 'Settings',
    'dashboard.settingsDesc': 'Configure your preferences',
    
    // Dashboard Stats
    'dashboard.totalDoctor': 'Total Doctor',
    'dashboard.totalUser': 'Total User',
    'dashboard.totalChamber': 'Total Chamber',
    'dashboard.totalIncome': 'Total Income',
    'dashboard.totalExpense': 'Total Expense',
    'dashboard.netIncome': 'Net Income',
    'dashboard.deposit': 'Deposit',
    'dashboard.cashInHand': 'Cash In Hand',
    
    // Dashboard Filters
    'dashboard.filters': 'Filters',
    'dashboard.filterByChamber': 'Filter by Chamber',
    'dashboard.filterByDoctor': 'Filter by Doctor',
    'dashboard.startDate': 'Start Date',
    'dashboard.endDate': 'End Date',
    'dashboard.allChambers': 'All Chambers',
    'dashboard.allDoctors': 'All Doctors',
    'dashboard.selectStartDate': 'Select start date',
    'dashboard.selectEndDate': 'Select end date',
    'dashboard.resetFilters': 'Reset Filters',
    'dashboard.applyFilters': 'Apply Filters',
    'dashboard.pickDate': 'Pick a date',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.doctor': 'Doctor',
    'sidebar.chamber': 'Chamber',
    'sidebar.user': 'User',
    'sidebar.appointment': 'Appointment',
    'sidebar.operation': 'Operation',
    'sidebar.operationType': 'Operation Type',
    'sidebar.expenditure': 'Expenditure',
    'sidebar.account': 'Bank Account',
    'sidebar.deposit': 'Deposit',
    'sidebar.docledger': 'DocLedger',
    'account.changePassword': 'Change Password',
    'account.superAdmin': 'Super Admin',
    'account.admin': 'Admin',
    'account.user': 'User',
    
    // Change Password
    'changePassword.currentPassword': 'Current Password',
    'changePassword.newPassword': 'New Password',
    'changePassword.confirmPassword': 'Confirm Password',
    'changePassword.currentPasswordPlaceholder': 'Enter current password',
    'changePassword.newPasswordPlaceholder': 'Enter new password',
    'changePassword.confirmPasswordPlaceholder': 'Confirm new password',
    'changePassword.currentPasswordRequired': 'Current password is required',
    'changePassword.newPasswordRequired': 'New password is required',
    'changePassword.confirmPasswordRequired': 'Confirm password is required',
    'changePassword.passwordsDoNotMatch': 'Passwords do not match',
    'changePassword.newPasswordSameAsCurrent': 'New password must be different from current password',
    'changePassword.changing': 'Changing...',
    'changePassword.changePassword': 'Change Password',
    'changePassword.passwordChanged': 'Password Changed',
    'changePassword.passwordChangedDesc': 'Your password has been changed successfully',
    
    // Common
    'common.language': 'Language',
    'common.search': 'Search',
    'common.cancel': 'Cancel',
    'common.create': 'Create',
    'common.creating': 'Creating...',
    
    // Auth
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter password',
    'auth.phonePlaceholder': '01XXXXXXXXX',
    
    // Validation
    'validation.nameRequired': 'Name is required',
    'validation.phoneRequired': 'Phone number is required',
    'validation.phoneLength': 'Phone number must be exactly 11 digits',
    'validation.phoneStart': 'Phone number must start with 01',
    'validation.phoneOperator': 'Invalid operator code (3rd digit must be 3-9)',
    'validation.passwordRequired': 'Password is required',
    'validation.passwordLength': 'Password must be at least 6 characters',
    'validation.invalidCredentials': 'Invalid credentials. Please try again.',
    
    // Toast
    'toast.success': 'Success',
    'toast.error': 'Error',
    'toast.warning': 'Warning',
    'toast.info': 'Information',
    'toast.close': 'Close',
    'toast.loginSuccess': 'Login Successful',
    'toast.loginSuccessDesc': 'Welcome back! You have been logged in successfully.',
    'toast.logoutSuccess': 'Logout Successful',
    'toast.logoutSuccessDesc': 'You have been logged out successfully.',
    'toast.loginError': 'Login Failed',
    'toast.loginErrorDesc': 'Invalid credentials. Please check your phone number and password.',
    
    // Calendar
    'calendar.today': 'Today',
    'calendar.previousMonth': 'Previous month',
    'calendar.nextMonth': 'Next month',
    'calendar.january': 'January',
    'calendar.february': 'February',
    'calendar.march': 'March',
    'calendar.april': 'April',
    'calendar.may': 'May',
    'calendar.june': 'June',
    'calendar.july': 'July',
    'calendar.august': 'August',
    'calendar.september': 'September',
    'calendar.october': 'October',
    'calendar.november': 'November',
    'calendar.december': 'December',
    
    // Doctor
    'doctor.title': 'Doctor Management',
    'doctor.subtitle': 'Manage doctors and their permissions',
    'doctor.search': 'Search doctors...',
    'doctor.searchPlaceholder': 'Search by name or phone number',
    'doctor.name': 'Name',
    'doctor.phoneNumber': 'Phone Number',
    'doctor.status': 'Status',
    'doctor.actions': 'Actions',
    'doctor.edit': 'Edit',
    'doctor.active': 'Active',
    'doctor.inactive': 'Inactive',
    'doctor.previous': 'Previous',
    'doctor.next': 'Next',
    'doctor.showing': 'Showing',
    'doctor.to': 'to',
    'doctor.of': 'of',
    'doctor.results': 'results',
    'doctor.addDoctor': 'Add Doctor',
    'doctor.addNewDoctor': 'Add New Doctor',
    'doctor.addNewDoctorDesc': 'Create a new doctor account',
    'doctor.namePlaceholder': 'Enter doctor name',
    'doctor.doctorAdded': 'Doctor Added',
    'doctor.doctorAddedDesc': 'New doctor has been created successfully',

    // Chamber
    'chamber.title': 'Chamber Management',
    'chamber.subtitle': 'Manage chambers and their details',
    'chamber.search': 'Search chambers...',
    'chamber.searchPlaceholder': 'Search by doctor name, chamber name or address',
    'chamber.doctorName': 'Doctor Name',
    'chamber.chamberName': 'Chamber Name',
    'chamber.address': 'Chamber Address',
    'chamber.status': 'Status',
    'chamber.actions': 'Actions',
    'chamber.edit': 'Edit',
    'chamber.active': 'Active',
    'chamber.inactive': 'Inactive',
    'chamber.previous': 'Previous',
    'chamber.next': 'Next',
    'chamber.showing': 'Showing',
    'chamber.to': 'to',
    'chamber.of': 'of',
    'chamber.results': 'results',
    'chamber.addChamber': 'Add Chamber',
    'chamber.addNewChamber': 'Add New Chamber',
    'chamber.addNewChamberDesc': 'Create a new chamber with doctor assignment',
    'chamber.selectDoctor': 'Select Doctor',
    'chamber.chamberNamePlaceholder': 'Enter chamber name',
    'chamber.addressPlaceholder': 'Enter chamber address',
    'chamber.chamberAdded': 'Chamber Added',
    'chamber.chamberAddedDesc': 'New chamber has been created successfully',
    'chamber.noChambers': 'No chambers found',
    'chamber.doctorRequired': 'Doctor selection is required',
    'chamber.chamberNameRequired': 'Chamber name is required',
    'chamber.addressRequired': 'Chamber address is required',

    // User
    'user.title': 'User Management',
    'user.subtitle': 'Manage users and their chamber assignments',
    'user.search': 'Search users...',
    'user.searchPlaceholder': 'Search by doctor name, chamber name, user name or phone number',
    'user.doctorName': 'Doctor Name',
    'user.chamberName': 'Chamber Name',
    'user.userName': 'User Name',
    'user.phoneNumber': 'Phone Number',
    'user.status': 'Status',
    'user.actions': 'Actions',
    'user.edit': 'Edit',
    'user.active': 'Active',
    'user.inactive': 'Inactive',
    'user.previous': 'Previous',
    'user.next': 'Next',
    'user.showing': 'Showing',
    'user.to': 'to',
    'user.of': 'of',
    'user.results': 'results',
    'user.addUser': 'Add User',
    'user.addNewUser': 'Add New User',
    'user.addNewUserDesc': 'Create a new user account with chamber assignment',
    'user.selectDoctor': 'Select Doctor',
    'user.selectChamber': 'Select Chamber',
    'user.selectDoctorFirst': 'Select doctor first',
    'user.userNamePlaceholder': 'Enter user name',
    'user.userAdded': 'User Added',
    'user.userAddedDesc': 'New user has been created successfully',
    'user.noUsers': 'No users found',
    'user.doctorRequired': 'Doctor selection is required',
    'user.chamberRequired': 'Chamber selection is required',
    'user.filterByChamber': 'Filter by Chamber',
    'user.allChambers': 'All Chambers',

    // Appointment
    'appointment.title': 'Appointment Management',
    'appointment.subtitle': 'Manage patient appointments and schedules',
    'appointment.search': 'Search appointments...',
    'appointment.searchPlaceholder': 'Search by doctor, chamber, patient name, type, phone, date, time or amount',
    'appointment.doctorName': 'Doctor Name',
    'appointment.chamberName': 'Chamber Name',
    'appointment.patientName': 'Patient Name',
    'appointment.patientType': 'Patient Type',
    'appointment.patientPhone': 'Patient Phone',
    'appointment.date': 'Date',
    'appointment.time': 'Time',
    'appointment.amount': 'Amount',
    'appointment.status': 'Status',
    'appointment.actions': 'Actions',
    'appointment.edit': 'Edit',
    'appointment.active': 'Active',
    'appointment.inactive': 'Inactive',
    'appointment.previous': 'Previous',
    'appointment.next': 'Next',
    'appointment.showing': 'Showing',
    'appointment.to': 'to',
    'appointment.of': 'of',
    'appointment.results': 'results',
    'appointment.addAppointment': 'Add Appointment',
    'appointment.addNewAppointment': 'Add New Appointment',
    'appointment.addNewAppointmentDesc': 'Schedule a new patient appointment',
    'appointment.selectDoctor': 'Select Doctor',
    'appointment.selectChamber': 'Select Chamber',
    'appointment.selectDoctorFirst': 'Select doctor first',
    'appointment.selectPatientType': 'Select Patient Type',
    'appointment.selectDate': 'Select appointment date',
    'appointment.selectTime': 'Select appointment time',
    'appointment.patientNamePlaceholder': 'Enter patient name',
    'appointment.amountPlaceholder': 'Enter amount (e.g., 1500.00)',
    'appointment.appointmentAdded': 'Appointment Added',
    'appointment.appointmentAddedDesc': 'New appointment has been scheduled successfully',
    'appointment.noAppointments': 'No appointments found',
    'appointment.doctorRequired': 'Doctor selection is required',
    'appointment.chamberRequired': 'Chamber selection is required',
    'appointment.patientNameRequired': 'Patient name is required',
    'appointment.patientTypeRequired': 'Patient type is required',
    'appointment.dateRequired': 'Appointment date is required',
    'appointment.timeRequired': 'Appointment time is required',
    'appointment.amountRequired': 'Amount is required',
    'appointment.invalidAmount': 'Please enter a valid amount',
    'appointment.pastDateNotAllowed': 'Past dates are not allowed',
    'appointment.filterByChamber': 'Filter by Chamber',
    'appointment.allChambers': 'All Chambers',
    
    // Operation
    'operation.title': 'Operation Management',
    'operation.subtitle': 'Manage patient operations and surgical procedures',
    'operation.search': 'Search operations...',
    'operation.searchPlaceholder': 'Search by doctor, chamber, patient name, operation type, phone, date, time or amount',
    'operation.doctorName': 'Doctor Name',
    'operation.chamberName': 'Chamber Name',
    'operation.patientName': 'Patient Name',
    'operation.operationType': 'Operation Type',
    'operation.patientPhone': 'Patient Phone',
    'operation.date': 'Date',
    'operation.time': 'Time',
    'operation.amount': 'Amount',
    'operation.status': 'Status',
    'operation.actions': 'Actions',
    'operation.edit': 'Edit',
    'operation.active': 'Active',
    'operation.inactive': 'Inactive',
    'operation.previous': 'Previous',
    'operation.next': 'Next',
    'operation.showing': 'Showing',
    'operation.to': 'to',
    'operation.of': 'of',
    'operation.results': 'results',
    'operation.addOperation': 'Add Operation',
    'operation.addNewOperation': 'Add New Operation',
    'operation.addNewOperationDesc': 'Schedule a new patient operation',
    'operation.selectDoctor': 'Select Doctor',
    'operation.selectChamber': 'Select Chamber',
    'operation.selectDoctorFirst': 'Select doctor first',
    'operation.selectOperationType': 'Select Operation Type',
    'operation.selectDate': 'Select operation date',
    'operation.selectTime': 'Select operation time',
    'operation.patientNamePlaceholder': 'Enter patient name',
    'operation.amountPlaceholder': 'Enter amount (e.g., 15000.00)',
    'operation.operationAdded': 'Operation Added',
    'operation.operationAddedDesc': 'New operation has been scheduled successfully',
    'operation.noOperations': 'No operations found',
    'operation.doctorRequired': 'Doctor selection is required',
    'operation.chamberRequired': 'Chamber selection is required',
    'operation.patientNameRequired': 'Patient name is required',
    'operation.operationTypeRequired': 'Operation type is required',
    'operation.dateRequired': 'Operation date is required',
    'operation.timeRequired': 'Operation time is required',
    'operation.amountRequired': 'Amount is required',
    'operation.invalidAmount': 'Please enter a valid amount',
    'operation.pastDateNotAllowed': 'Past dates are not allowed',
    'operation.filterByChamber': 'Filter by Chamber',
    'operation.allChambers': 'All Chambers',
    
    // Operation Type
    'operationType.title': 'Operation Type Management',
    'operationType.subtitle': 'Manage operation types for different chambers',
    'operationType.search': 'Search operation types...',
    'operationType.searchPlaceholder': 'Search by doctor name, chamber name or operation type',
    'operationType.doctorName': 'Doctor Name',
    'operationType.chamberName': 'Chamber Name',
    'operationType.operationType': 'Operation Type',
    'operationType.status': 'Status',
    'operationType.actions': 'Actions',
    'operationType.edit': 'Edit',
    'operationType.active': 'Active',
    'operationType.inactive': 'Inactive',
    'operationType.previous': 'Previous',
    'operationType.next': 'Next',
    'operationType.showing': 'Showing',
    'operationType.to': 'to',
    'operationType.of': 'of',
    'operationType.results': 'results',
    'operationType.addOperationType': 'Add Operation Type',
    'operationType.addNewOperationType': 'Add New Operation Type',
    'operationType.addNewOperationTypeDesc': 'Create a new operation type for a chamber',
    'operationType.selectDoctor': 'Select Doctor',
    'operationType.selectChamber': 'Select Chamber',
    'operationType.selectDoctorFirst': 'Select doctor first',
    'operationType.operationTypePlaceholder': 'Enter operation type name',
    'operationType.operationTypeAdded': 'Operation Type Added',
    'operationType.operationTypeAddedDesc': 'New operation type has been created successfully',
    'operationType.noOperationTypes': 'No operation types found',
    'operationType.doctorRequired': 'Doctor selection is required',
    'operationType.chamberRequired': 'Chamber selection is required',
    'operationType.operationTypeRequired': 'Operation type is required',
    'operationType.filterByChamber': 'Filter by Chamber',
    'operationType.allChambers': 'All Chambers',
    
    // Expenditure
    'expenditure.title': 'Expenditure Management',
    'expenditure.subtitle': 'Manage chamber expenditures and financial records',
    'expenditure.search': 'Search expenditures...',
    'expenditure.searchPlaceholder': 'Search by doctor, chamber, expenditure details or amount',
    'expenditure.doctorName': 'Doctor Name',
    'expenditure.chamberName': 'Chamber Name',
    'expenditure.expenditureDetails': 'Expenditure Details',
    'expenditure.amount': 'Amount',
    'expenditure.status': 'Status',
    'expenditure.actions': 'Actions',
    'expenditure.edit': 'Edit',
    'expenditure.view': 'View',
    'expenditure.download': 'Download',
    'expenditure.active': 'Active',
    'expenditure.inactive': 'Inactive',
    'expenditure.previous': 'Previous',
    'expenditure.next': 'Next',
    'expenditure.showing': 'Showing',
    'expenditure.to': 'to',
    'expenditure.of': 'of',
    'expenditure.results': 'results',
    'expenditure.addExpenditure': 'Add Expenditure',
    'expenditure.addNewExpenditure': 'Add New Expenditure',
    'expenditure.addNewExpenditureDesc': 'Record a new expenditure with details and attachment',
    'expenditure.selectDoctor': 'Select Doctor',
    'expenditure.selectChamber': 'Select Chamber',
    'expenditure.selectDoctorFirst': 'Select doctor first',
    'expenditure.expenditureDetailsPlaceholder': 'Enter expenditure details...',
    'expenditure.amountPlaceholder': 'Enter amount (e.g., 5000.00)',
    'expenditure.attachment': 'Attachment',
    'expenditure.attachments': 'Attachments',
    'expenditure.attachmentHelper': 'Accepted formats: JPG, PNG, JPEG, PDF (Max 10MB)',
    'expenditure.chooseFiles': 'Choose Files',
    'expenditure.chooseFile': 'Choose File',
    'expenditure.noFileChosen': 'No file chosen',
    'expenditure.filesSelected': 'files selected',
    'expenditure.fileSelected': 'file selected',
    'expenditure.dragDropFiles': 'Drag & drop files here or click to browse',
    'expenditure.addMoreFiles': 'Add More Files',
    'expenditure.multipleFilesTip': 'You can select multiple files at once or add more files by clicking here again',
    'expenditure.preview': 'Preview',
    'expenditure.selectedFile': 'Selected File',
    'expenditure.selectedFiles': 'Selected Files',
    'expenditure.uploadedFiles': 'Uploaded Files',
    'expenditure.remove': 'Remove',
    'expenditure.expenditureAdded': 'Expenditure Added',
    'expenditure.expenditureAddedDesc': 'New expenditure has been recorded successfully',
    'expenditure.noExpenditures': 'No expenditures found',
    'expenditure.doctorRequired': 'Doctor selection is required',
    'expenditure.chamberRequired': 'Chamber selection is required',
    'expenditure.expenditureDetailsRequired': 'Expenditure details are required',
    'expenditure.amountRequired': 'Amount is required',
    'expenditure.attachmentRequired': 'Attachment is required',
    'expenditure.invalidAmount': 'Please enter a valid amount',
    'expenditure.filterByChamber': 'Filter by Chamber',
    'expenditure.allChambers': 'All Chambers',
    
    // Deposit
    'deposit.title': 'Deposit Management',
    'deposit.subtitle': 'Manage chamber deposits and financial records',
    'deposit.search': 'Search deposits...',
    'deposit.searchPlaceholder': 'Search by doctor, chamber, account or amount',
    'deposit.doctorName': 'Doctor Name',
    'deposit.chamberName': 'Chamber Name',
    'deposit.account': 'Account',
    'deposit.amount': 'Amount',
    'deposit.status': 'Status',
    'deposit.actions': 'Actions',
    'deposit.edit': 'Edit',
    'deposit.view': 'View',
    'deposit.download': 'Download',
    'deposit.active': 'Active',
    'deposit.inactive': 'Inactive',
    'deposit.previous': 'Previous',
    'deposit.next': 'Next',
    'deposit.showing': 'Showing',
    'deposit.to': 'to',
    'deposit.of': 'of',
    'deposit.results': 'results',
    'deposit.addDeposit': 'Add Deposit',
    'deposit.addNewDeposit': 'Add New Deposit',
    'deposit.addNewDepositDesc': 'Record a new deposit with details and attachment',
    'deposit.selectDoctor': 'Select Doctor',
    'deposit.selectChamber': 'Select Chamber',
    'deposit.selectAccount': 'Select Account',
    'deposit.selectDoctorFirst': 'Select doctor first',
    'deposit.amountPlaceholder': 'Enter amount (e.g., 5000.00)',
    'deposit.attachment': 'Attachment',
    'deposit.attachments': 'Attachments',
    'deposit.attachmentHelper': 'Accepted formats: JPG, PNG, JPEG, PDF (Max 10MB)',
    'deposit.chooseFiles': 'Choose Files',
    'deposit.chooseFile': 'Choose File',
    'deposit.noFileChosen': 'No file chosen',
    'deposit.filesSelected': 'files selected',
    'deposit.fileSelected': 'file selected',
    'deposit.dragDropFiles': 'Drag & drop files here or click to browse',
    'deposit.addMoreFiles': 'Add More Files',
    'deposit.multipleFilesTip': 'You can select multiple files at once or add more files by clicking here again',
    'deposit.preview': 'Preview',
    'deposit.selectedFile': 'Selected File',
    'deposit.selectedFiles': 'Selected Files',
    'deposit.uploadedFiles': 'Uploaded Files',
    'deposit.remove': 'Remove',
    'deposit.depositAdded': 'Deposit Added',
    'deposit.depositAddedDesc': 'New deposit has been recorded successfully',
    'deposit.noDeposits': 'No deposits found',
    'deposit.doctorRequired': 'Doctor selection is required',
    'deposit.chamberRequired': 'Chamber selection is required',
    'deposit.accountRequired': 'Account selection is required',
    'deposit.amountRequired': 'Amount is required',
    'deposit.attachmentRequired': 'Attachment is required',
    'deposit.invalidAmount': 'Please enter a valid amount',
    'deposit.filterByChamber': 'Filter by Chamber',
    'deposit.allChambers': 'All Chambers',
    
    // Account
    'account.title': 'Bank Account Management',
    'account.subtitle': 'Manage bank accounts and financial information',
    'account.search': 'Search accounts...',
    'account.searchPlaceholder': 'Search by doctor, account type, organization or account number',
    'account.doctorName': 'Doctor Name',
    'account.accountType': 'Account Type',
    'account.accountOrganization': 'Account Organization',
    'account.accountNumber': 'Account Number',
    'account.status': 'Status',
    'account.actions': 'Actions',
    'account.edit': 'Edit',
    'account.view': 'View',
    'account.active': 'Active',
    'account.inactive': 'Inactive',
    'account.previous': 'Previous',
    'account.next': 'Next',
    'account.showing': 'Showing',
    'account.to': 'to',
    'account.of': 'of',
    'account.results': 'results',
    'account.addAccount': 'Add Account',
    'account.addNewAccount': 'Add New Account',
    'account.addNewAccountDesc': 'Add a new account with details and information',
    'account.selectDoctor': 'Select Doctor',
    'account.selectAccountType': 'Select Account Type',
    'account.selectDoctorFirst': 'Select doctor first',
    'account.accountOrganizationPlaceholder': 'e.g., bKash, Brac Bank, Islami Bank',
    'account.accountNumberPlaceholder': 'Enter account number',
    'account.accountAdded': 'Account Added',
    'account.accountAddedDesc': 'New account has been added successfully',
    'account.noAccounts': 'No accounts found',
    'account.doctorRequired': 'Doctor selection is required',
    'account.accountTypeRequired': 'Account type selection is required',
    'account.accountOrganizationRequired': 'Account organization is required',
    'account.accountNumberRequired': 'Account number is required',
    'account.invalidAccountNumber': 'Please enter a valid account number',
    'account.mfs': 'MFS',
    'account.bank': 'Bank',
    'account.mfsFormatHint': 'Format: 01XXXXXXXX (11 digits, 3rd digit must be 3-9)',
    'account.bankFormatHint': 'Format: 8-18 digit bank account number',
  },
  bn: {
    // Login Form
    'login.title': 'স্বাগতম',
    'login.subtitle': 'আপনার ডকলেজার অ্যাকাউন্টে সাইন ইন করুন',
    'login.phone': 'ফোন নম্বর',
    'login.phonePlaceholder': '০১XXXXXXXXX',
    'login.password': 'পাসওয়ার্ড',
    'login.passwordPlaceholder': 'আপনার পাসওয়ার্ড লিখুন',
    'login.signingIn': 'সাইন ইন করা হচ্ছে...',
    'login.signIn': 'সাইন ইন',
    'login.needHelp': 'সাহায্য প্রয়োজন? যোগাযোগ করুন',
    'login.allRightsReserved': 'সর্বস্বত্ব সংরক্ষিত',
    
    // Login Page
    'login.brandTitle': 'ডকলেজার',
    'login.brandSubtitle': 'আপনার ডকুমেন্ট ওয়ার্কফ্লো সহজ করুন',
    
    // Dashboard
    'dashboard.welcome': 'ড্যাশবোর্ডে স্বাগতম',
    'dashboard.logout': 'লগ আউট',
    'dashboard.title': 'ড্যাশবোর্ড',
    'dashboard.subtitle': 'আপনার ডকলেজার ড্যাশবোর্ডে স্বাগতম',
    'dashboard.documents': 'ডকুমেন্ট',
    'dashboard.documentsDesc': 'এখানে আপনার ডকুমেন্ট পরিচালনা করুন',
    'dashboard.reports': 'রিপোর্ট',
    'dashboard.reportsDesc': 'রিপোর্ট দেখুন এবং তৈরি করুন',
    'dashboard.settings': 'সেটিংস',
    'dashboard.settingsDesc': 'আপনার পছন্দ কনফিগার করুন',
    
    // Dashboard Stats
    'dashboard.totalDoctor': 'মোট ডাক্তার',
    'dashboard.totalUser': 'মোট ইউজার',
    'dashboard.totalChamber': 'মোট চেম্বার',
    'dashboard.totalIncome': 'মোট আয়',
    'dashboard.totalExpense': 'মোট ব্যয়',
    'dashboard.netIncome': 'নেট আয়',
    'dashboard.deposit': 'জমা',
    'dashboard.cashInHand': 'হাতে নগদ',
    
    // Dashboard Filters
    'dashboard.filters': 'ফিল্টার',
    'dashboard.filterByChamber': 'চেম্বার দিয়ে ফিল্টার',
    'dashboard.filterByDoctor': 'ডাক্তার দিয়ে ফিল্টার',
    'dashboard.startDate': 'শুরুর তারিখ',
    'dashboard.endDate': 'শেষের তারিখ',
    'dashboard.allChambers': 'সকল চেম্বার',
    'dashboard.allDoctors': 'সকল ডাক্তার',
    'dashboard.selectStartDate': 'শুরুর তারিখ নির্বাচন করুন',
    'dashboard.selectEndDate': 'শেষের তারিখ নির্বাচন করুন',
    'dashboard.resetFilters': 'ফিল্টার রিসেট',
    'dashboard.applyFilters': 'ফিল্টার প্রয়োগ',
    'dashboard.pickDate': 'তারিখ নির্বাচন করুন',
    
    // Sidebar
    'sidebar.dashboard': 'ড্যাশবোর্ড',
    'sidebar.doctor': 'ডাক্তার',
    'sidebar.chamber': 'চেম্বার',
    'sidebar.user': 'ইউজার',
    'sidebar.appointment': 'অ্যাপয়েন্টমেন্ট',
    'sidebar.operation': 'অপারেশন',
    'sidebar.operationType': 'অপারেশন টাইপ',
    'sidebar.expenditure': 'ব্যয়',
    'sidebar.account': 'ব্যাংক অ্যাকাউন্ট',
    'sidebar.deposit': 'জমা',
    'sidebar.docledger': 'ডকলেজার',
    'account.changePassword': 'পাসওয়ার্ড পরিবর্তন',
    'account.superAdmin': 'সুপার অ্যাডমিন',
    'account.admin': 'অ্যাডমিন',
    'account.user': 'ইউজার',
    
    // Change Password
    'changePassword.currentPassword': 'বর্তমান পাসওয়ার্ড',
    'changePassword.newPassword': 'নতুন পাসওয়ার্ড',
    'changePassword.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    'changePassword.currentPasswordPlaceholder': 'বর্তমান পাসওয়ার্ড লিখুন',
    'changePassword.newPasswordPlaceholder': 'নতুন পাসওয়ার্ড লিখুন',
    'changePassword.confirmPasswordPlaceholder': 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
    'changePassword.currentPasswordRequired': 'বর্তমান পাসওয়ার্ড প্রয়োজন',
    'changePassword.newPasswordRequired': 'নতুন পাসওয়ার্ড প্রয়োজন',
    'changePassword.confirmPasswordRequired': 'পাসওয়ার্ড নিশ্চিতকরণ প্রয়োজন',
    'changePassword.passwordsDoNotMatch': 'পাসওয়ার্ড মিলছে না',
    'changePassword.newPasswordSameAsCurrent': 'নতুন পাসওয়ার্ড বর্তমান পাসওয়ার্ড থেকে আলাদা হতে হবে',
    'changePassword.changing': 'পরিবর্তন করা হচ্ছে...',
    'changePassword.changePassword': 'পাসওয়ার্ড পরিবর্তন করুন',
    'changePassword.passwordChanged': 'পাসওয়ার্ড পরিবর্তিত হয়েছে',
    'changePassword.passwordChangedDesc': 'আপনার পাসওয়ার্ড সফলভাবে পরিবর্তিত হয়েছে',
    
    // Validation
    'validation.phoneRequired': 'ফোন নম্বর প্রয়োজন',
    'validation.phoneLength': 'ফোন নম্বর অবশ্যই ১১ সংখ্যার হতে হবে',
    'validation.phoneStart': 'ফোন নম্বর অবশ্যই ০১ দিয়ে শুরু হতে হবে',
    'validation.phoneOperator': 'অবৈধ অপারেটর কোড (৩য় সংখ্যা ৩-৯ হতে হবে)',
    'validation.passwordRequired': 'পাসওয়ার্ড প্রয়োজন',
    'validation.passwordLength': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে',
    'validation.invalidCredentials': 'অবৈধ প্রমাণপত্র। আবার চেষ্টা করুন।',
    
    // Common
    'common.language': 'ভাষা',
    'common.search': 'খুঁজুন',
    'common.cancel': 'বাতিল',
    'common.create': 'তৈরি',
    'common.creating': 'তৈরি করা হচ্ছে...',
    
    // Auth
    'auth.password': 'পাসওয়ার্ড',
    'auth.passwordPlaceholder': 'পাসওয়ার্ড লিখুন',
    'auth.phonePlaceholder': '০১XXXXXXXXX',
    
    // Validation
    'validation.nameRequired': 'নাম প্রয়োজন',
    
    // Toast
    'toast.success': 'সফল',
    'toast.error': 'ত্রুটি',
    'toast.warning': 'সতর্কতা',
    'toast.info': 'তথ্য',
    'toast.close': 'বন্ধ করুন',
    'toast.loginSuccess': 'লগইন সফল',
    'toast.loginSuccessDesc': 'স্বাগতম! আপনি সফলভাবে লগইন করেছেন।',
    'toast.logoutSuccess': 'লগআউট সফল',
    'toast.logoutSuccessDesc': 'আপনি সফলভাবে লগআউট করেছেন।',
    'toast.loginError': 'লগইন ব্যর্থ',
    'toast.loginErrorDesc': 'অবৈধ প্রমাণপত্র। অনুগ্রহ করে আপনার ফোন নম্বর এবং পাসওয়ার্ড পরীক্ষা করুন।',
    
    // Calendar
    'calendar.today': 'আজ',
    'calendar.previousMonth': 'পূর্ববর্তী মাস',
    'calendar.nextMonth': 'পরবর্তী মাস',
    'calendar.january': 'জানুয়ারী',
    'calendar.february': 'ফেব্রুয়ারী',
    'calendar.march': 'মার্চ',
    'calendar.april': 'এপ্রিল',
    'calendar.may': 'মে',
    'calendar.june': 'জুন',
    'calendar.july': 'জুলাই',
    'calendar.august': 'আগস্ট',
    'calendar.september': 'সেপ্টেম্বর',
    'calendar.october': 'অক্টোবর',
    'calendar.november': 'নভেম্বর',
    'calendar.december': 'ডিসেম্বর',
    
    // Doctor
    'doctor.title': 'ডাক্তার ব্যবস্থাপনা',
    'doctor.subtitle': 'ডাক্তার এবং তাদের অনুমতি পরিচালনা করুন',
    'doctor.search': 'ডাক্তার খুঁজুন...',
    'doctor.searchPlaceholder': 'নাম বা ফোন নম্বর দিয়ে খুঁজুন',
    'doctor.name': 'নাম',
    'doctor.phoneNumber': 'ফোন নম্বর',
    'doctor.status': 'অবস্থা',
    'doctor.actions': 'কার্যক্রম',
    'doctor.edit': 'সম্পাদনা',
    'doctor.active': 'সক্রিয়',
    'doctor.inactive': 'নিষ্ক্রিয়',
    'doctor.previous': 'পূর্ববর্তী',
    'doctor.next': 'পরবর্তী',
    'doctor.showing': 'দেখানো হচ্ছে',
    'doctor.to': 'থেকে',
    'doctor.of': 'এর মধ্যে',
    'doctor.results': 'ফলাফল',
    'doctor.addDoctor': 'ডাক্তার যোগ করুন',
    'doctor.addNewDoctor': 'নতুন ডাক্তার যোগ করুন',
    'doctor.addNewDoctorDesc': 'একটি নতুন ডাক্তার অ্যাকাউন্ট তৈরি করুন',
    'doctor.namePlaceholder': 'ডাক্তারের নাম লিখুন',
    'doctor.doctorAdded': 'ডাক্তার যোগ করা হয়েছে',
    'doctor.doctorAddedDesc': 'নতুন ডাক্তার সফলভাবে তৈরি করা হয়েছে',

    // Chamber
    'chamber.title': 'চেম্বার ব্যবস্থাপনা',
    'chamber.subtitle': 'চেম্বার এবং তাদের বিবরণ পরিচালনা করুন',
    'chamber.search': 'চেম্বার খুঁজুন...',
    'chamber.searchPlaceholder': 'ডাক্তারের নাম, চেম্বারের নাম বা ঠিকানা দিয়ে খুঁজুন',
    'chamber.doctorName': 'ডাক্তারের নাম',
    'chamber.chamberName': 'চেম্বারের নাম',
    'chamber.address': 'চেম্বারের ঠিকানা',
    'chamber.status': 'অবস্থা',
    'chamber.actions': 'কার্যক্রম',
    'chamber.edit': 'সম্পাদনা',
    'chamber.active': 'সক্রিয়',
    'chamber.inactive': 'নিষ্ক্রিয়',
    'chamber.previous': 'পূর্ববর্তী',
    'chamber.next': 'পরবর্তী',
    'chamber.showing': 'দেখানো হচ্ছে',
    'chamber.to': 'থেকে',
    'chamber.of': 'এর মধ্যে',
    'chamber.results': 'ফলাফল',
    'chamber.addChamber': 'চেম্বার যোগ করুন',
    'chamber.addNewChamber': 'নতুন চেম্বার যোগ করুন',
    'chamber.addNewChamberDesc': 'ডাক্তার নিয়োগ সহ একটি নতুন চেম্বার তৈরি করুন',
    'chamber.selectDoctor': 'ডাক্তার নির্বাচন করুন',
    'chamber.chamberNamePlaceholder': 'চেম্বারের নাম লিখুন',
    'chamber.addressPlaceholder': 'চেম্বারের ঠিকানা লিখুন',
    'chamber.chamberAdded': 'চেম্বার যোগ করা হয়েছে',
    'chamber.chamberAddedDesc': 'নতুন চেম্বার সফলভাবে তৈরি করা হয়েছে',
    'chamber.noChambers': 'কোন চেম্বার পাওয়া যায়নি',
    'chamber.doctorRequired': 'ডাক্তার নির্বাচন প্রয়োজন',
    'chamber.chamberNameRequired': 'চেম্বারের নাম প্রয়োজন',
    'chamber.addressRequired': 'চেম্বারের ঠিকানা প্রয়োজন',

    // User
    'user.title': 'ইউজার ব্যবস্থাপনা',
    'user.subtitle': 'ইউজার এবং তাদের চেম্বার নিয়োগ পরিচালনা করুন',
    'user.search': 'ইউজার খুঁজুন...',
    'user.searchPlaceholder': 'ডাক্তারের নাম, চেম্বারের নাম, ইউজারের নাম বা ফোন নম্বর দিয়ে খুঁজুন',
    'user.doctorName': 'ডাক্তারের নাম',
    'user.chamberName': 'চেম্বারের নাম',
    'user.userName': 'ইউজারের নাম',
    'user.phoneNumber': 'ফোন নম্বর',
    'user.status': 'অবস্থা',
    'user.actions': 'কার্যক্রম',
    'user.edit': 'সম্পাদনা',
    'user.active': 'সক্রিয়',
    'user.inactive': 'নিষ্ক্রিয়',
    'user.previous': 'পূর্ববর্তী',
    'user.next': 'পরবর্তী',
    'user.showing': 'দেখানো হচ্ছে',
    'user.to': 'থেকে',
    'user.of': 'এর মধ্যে',
    'user.results': 'ফলাফল',
    'user.addUser': 'ইউজার যোগ করুন',
    'user.addNewUser': 'নতুন ইউজার যোগ করুন',
    'user.addNewUserDesc': 'চেম্বার নিয়োগ সহ একটি নতুন ইউজার অ্যাকাউন্ট তৈরি করুন',
    'user.selectDoctor': 'ডাক্তার নির্বাচন করুন',
    'user.selectChamber': 'চেম্বার নির্বাচন করুন',
    'user.selectDoctorFirst': 'প্রথমে ডাক্তার নির্বাচন করুন',
    'user.userNamePlaceholder': 'ইউজারের নাম লিখুন',
    'user.userAdded': 'ইউজার যোগ করা হয়েছে',
    'user.userAddedDesc': 'নতুন ইউজার সফলভাবে তৈরি করা হয়েছে',
    'user.noUsers': 'কোন ইউজার পাওয়া যায়নি',
    'user.doctorRequired': 'ডাক্তার নির্বাচন প্রয়োজন',
    'user.chamberRequired': 'চেম্বার নির্বাচন প্রয়োজন',
    'user.filterByChamber': 'চেম্বার দিয়ে ফিল্টার',
    'user.allChambers': 'সকল চেম্বার',

    // Appointment
    'appointment.title': 'অ্যাপয়েন্টমেন্ট ব্যবস্থাপনা',
    'appointment.subtitle': 'রোগীর অ্যাপয়েন্টমেন্ট এবং সময়সূচী পরিচালনা করুন',
    'appointment.search': 'অ্যাপয়েন্টমেন্ট খুঁজুন...',
    'appointment.searchPlaceholder': 'ডাক্তার, চেম্বার, রোগীর নাম, ধরন, ফোন, তারিখ, সময় বা টাকার পরিমাণ দিয়ে খুঁজুন',
    'appointment.doctorName': 'ডাক্তারের নাম',
    'appointment.chamberName': 'চেম্বারের নাম',
    'appointment.patientName': 'রোগীর নাম',
    'appointment.patientType': 'রোগীর ধরন',
    'appointment.patientPhone': 'রোগীর ফোন',
    'appointment.date': 'তারিখ',
    'appointment.time': 'সময়',
    'appointment.amount': 'টাকার পরিমাণ',
    'appointment.status': 'অবস্থা',
    'appointment.actions': 'কার্যক্রম',
    'appointment.edit': 'সম্পাদনা',
    'appointment.active': 'সক্রিয়',
    'appointment.inactive': 'নিষ্ক্রিয়',
    'appointment.previous': 'পূর্ববর্তী',
    'appointment.next': 'পরবর্তী',
    'appointment.showing': 'দেখানো হচ্ছে',
    'appointment.to': 'থেকে',
    'appointment.of': 'এর মধ্যে',
    'appointment.results': 'ফলাফল',
    'appointment.addAppointment': 'অ্যাপয়েন্টমেন্ট যোগ করুন',
    'appointment.addNewAppointment': 'নতুন অ্যাপয়েন্টমেন্ট যোগ করুন',
    'appointment.addNewAppointmentDesc': 'একটি নতুন রোগী অ্যাপয়েন্টমেন্ট নির্ধারণ করুন',
    'appointment.selectDoctor': 'ডাক্তার নির্বাচন করুন',
    'appointment.selectChamber': 'চেম্বার নির্বাচন করুন',
    'appointment.selectDoctorFirst': 'প্রথমে ডাক্তার নির্বাচন করুন',
    'appointment.selectPatientType': 'রোগীর ধরন নির্বাচন করুন',
    'appointment.selectDate': 'অ্যাপয়েন্টমেন্ট তারিখ নির্বাচন করুন',
    'appointment.selectTime': 'অ্যাপয়েন্টমেন্ট সময় নির্বাচন করুন',
    'appointment.patientNamePlaceholder': 'রোগীর নাম লিখুন',
    'appointment.amountPlaceholder': 'টাকার পরিমাণ লিখুন (যেমন, ১৫০০.০০)',
    'appointment.appointmentAdded': 'অ্যাপয়েন্টমেন্ট যোগ করা হয়েছে',
    'appointment.appointmentAddedDesc': 'নতুন অ্যাপয়েন্টমেন্ট সফলভাবে নির্ধারণ করা হয়েছে',
    'appointment.noAppointments': 'কোন অ্যাপয়েন্টমেন্ট পাওয়া যায়নি',
    'appointment.doctorRequired': 'ডাক্তার নির্বাচন প্রয়োজন',
    'appointment.chamberRequired': 'চেম্বার নির্বাচন প্রয়োজন',
    'appointment.patientNameRequired': 'রোগীর নাম প্রয়োজন',
    'appointment.patientTypeRequired': 'রোগীর ধরন প্রয়োজন',
    'appointment.dateRequired': 'অ্যাপয়েন্টমেন্ট তারিখ প্রয়োজন',
    'appointment.timeRequired': 'অ্যাপয়েন্টমেন্ট সময় প্রয়োজন',
    'appointment.amountRequired': 'টাকার পরিমাণ প্রয়োজন',
    'appointment.invalidAmount': 'অনুগ্রহ করে একটি বৈধ টাকার পরিমাণ লিখুন',
    'appointment.pastDateNotAllowed': 'অতীতের তারিখ অনুমোদিত নয়',
    'appointment.filterByChamber': 'চেম্বার দিয়ে ফিল্টার',
    'appointment.allChambers': 'সকল চেম্বার',
    
    // Operation
    'operation.title': 'অপারেশন ব্যবস্থাপনা',
    'operation.subtitle': 'রোগীর অপারেশন এবং সার্জিক্যাল প্রক্রিয়া পরিচালনা করুন',
    'operation.search': 'অপারেশন খুঁজুন...',
    'operation.searchPlaceholder': 'ডাক্তার, চেম্বার, রোগীর নাম, অপারেশনের ধরন, ফোন, তারিখ, সময় বা টাকার পরিমাণ দিয়ে খুঁজুন',
    'operation.doctorName': 'ডাক্তারের নাম',
    'operation.chamberName': 'চেম্বারের নাম',
    'operation.patientName': 'রোগীর নাম',
    'operation.operationType': 'অপারেশনের ধরন',
    'operation.patientPhone': 'রোগীর ফোন',
    'operation.date': 'তারিখ',
    'operation.time': 'সময়',
    'operation.amount': 'টাকার পরিমাণ',
    'operation.status': 'অবস্থা',
    'operation.actions': 'কার্যক্রম',
    'operation.edit': 'সম্পাদনা',
    'operation.active': 'সক্রিয়',
    'operation.inactive': 'নিষ্ক্রিয়',
    'operation.previous': 'পূর্ববর্তী',
    'operation.next': 'পরবর্তী',
    'operation.showing': 'দেখানো হচ্ছে',
    'operation.to': 'থেকে',
    'operation.of': 'এর মধ্যে',
    'operation.results': 'ফলাফল',
    'operation.addOperation': 'অপারেশন যোগ করুন',
    'operation.addNewOperation': 'নতুন অপারেশন যোগ করুন',
    'operation.addNewOperationDesc': 'একটি নতুন রোগী অপারেশন নির্ধারণ করুন',
    'operation.selectDoctor': 'ডাক্তার নির্বাচন করুন',
    'operation.selectChamber': 'চেম্বার নির্বাচন করুন',
    'operation.selectDoctorFirst': 'প্রথমে ডাক্তার নির্বাচন করুন',
    'operation.selectOperationType': 'অপারেশনের ধরন নির্বাচন করুন',
    'operation.selectDate': 'অপারেশন তারিখ নির্বাচন করুন',
    'operation.selectTime': 'অপারেশন সময় নির্বাচন করুন',
    'operation.patientNamePlaceholder': 'রোগীর নাম লিখুন',
    'operation.amountPlaceholder': 'টাকার পরিমাণ লিখুন (যেমন, ১৫০০০.০০)',
    'operation.operationAdded': 'অপারেশন যোগ করা হয়েছে',
    'operation.operationAddedDesc': 'নতুন অপারেশন সফলভাবে নির্ধারণ করা হয়েছে',
    'operation.noOperations': 'কোন অপারেশন পাওয়া যায়নি',
    'operation.doctorRequired': 'ডাক্তার নির্বাচন প্রয়োজন',
    'operation.chamberRequired': 'চেম্বার নির্বাচন প্রয়োজন',
    'operation.patientNameRequired': 'রোগীর নাম প্রয়োজন',
    'operation.operationTypeRequired': 'অপারেশনের ধরন প্রয়োজন',
    'operation.dateRequired': 'অপারেশন তারিখ প্রয়োজন',
    'operation.timeRequired': 'অপারেশন সময় প্রয়োজন',
    'operation.amountRequired': 'টাকার পরিমাণ প্রয়োজন',
    'operation.invalidAmount': 'অনুগ্রহ করে একটি বৈধ টাকার পরিমাণ লিখুন',
    'operation.pastDateNotAllowed': 'অতীতের তারিখ অনুমোদিত নয়',
    'operation.filterByChamber': 'চেম্বার দিয়ে ফিল্টার',
    'operation.allChambers': 'সকল চেম্বার',
    
    // Operation Type
    'operationType.title': 'অপারেশন টাইপ ব্যবস্থাপনা',
    'operationType.subtitle': 'বিভিন্ন চেম্বারের জন্য অপারেশন টাইপ পরিচালনা করুন',
    'operationType.search': 'অপারেশন টাইপ খুঁজুন...',
    'operationType.searchPlaceholder': 'ডাক্তারের নাম, চেম্বারের নাম বা অপারেশন টাইপ দিয়ে খুঁজুন',
    'operationType.doctorName': 'ডাক্তারের নাম',
    'operationType.chamberName': 'চেম্বারের নাম',
    'operationType.operationType': 'অপারেশন টাইপ',
    'operationType.status': 'অবস্থা',
    'operationType.actions': 'কার্যক্রম',
    'operationType.edit': 'সম্পাদনা',
    'operationType.active': 'সক্রিয়',
    'operationType.inactive': 'নিষ্ক্রিয়',
    'operationType.previous': 'পূর্ববর্তী',
    'operationType.next': 'পরবর্তী',
    'operationType.showing': 'দেখানো হচ্ছে',
    'operationType.to': 'থেকে',
    'operationType.of': 'এর মধ্যে',
    'operationType.results': 'ফলাফল',
    'operationType.addOperationType': 'অপারেশন টাইপ যোগ করুন',
    'operationType.addNewOperationType': 'নতুন অপারেশন টাইপ যোগ করুন',
    'operationType.addNewOperationTypeDesc': 'একটি চেম্বারের জন্য নতুন অপারেশন টাইপ তৈরি করুন',
    'operationType.selectDoctor': 'ডাক্তার নির্বাচন করুন',
    'operationType.selectChamber': 'চেম্বার নির্বাচন করুন',
    'operationType.selectDoctorFirst': 'প্রথমে ডাক্তার নির্বাচন করুন',
    'operationType.operationTypePlaceholder': 'অপারেশন টাইপের নাম লিখুন',
    'operationType.operationTypeAdded': 'অপারেশন টাইপ যোগ করা হয়েছে',
    'operationType.operationTypeAddedDesc': 'নতুন অপারেশন টাইপ সফলভাবে তৈরি করা হয়েছে',
    'operationType.noOperationTypes': 'কোন অপারেশন টাইপ পাওয়া যায়নি',
    'operationType.doctorRequired': 'ডাক্তার নির্বাচন প্রয়োজন',
    'operationType.chamberRequired': 'চেম্বার নির্বাচন প্রয়োজন',
    'operationType.operationTypeRequired': 'অপারেশন টাইপ প্রয়োজন',
    'operationType.filterByChamber': 'চেম্বার দিয়ে ফিল্টার',
    'operationType.allChambers': 'সকল চেম্বার',
    
    // Expenditure
    'expenditure.title': 'ব্যয় ব্যবস্থাপনা',
    'expenditure.subtitle': 'চেম্বারের ব্যয় এবং আর্থিক রেকর্ড পরিচালনা করুন',
    'expenditure.search': 'ব্যয় খুঁজুন...',
    'expenditure.searchPlaceholder': 'ডাক্তার, চেম্বার, ব্যয়ের বিবরণ বা টাকার পরিমাণ দিয়ে খুঁজুন',
    'expenditure.doctorName': 'ডাক্তারের নাম',
    'expenditure.chamberName': 'চেম্বারের নাম',
    'expenditure.expenditureDetails': 'ব্যয়ের বিবরণ',
    'expenditure.amount': 'টাকার পরিমাণ',
    'expenditure.status': 'অবস্থা',
    'expenditure.actions': 'কার্যক্রম',
    'expenditure.edit': 'সম্পাদনা',
    'expenditure.view': 'দেখুন',
    'expenditure.download': 'ডাউনলোড',
    'expenditure.active': 'সক্রিয়',
    'expenditure.inactive': 'নিষ্ক্রিয়',
    'expenditure.previous': 'পূর্ববর্তী',
    'expenditure.next': 'পরবর্তী',
    'expenditure.showing': 'দেখানো হচ্ছে',
    'expenditure.to': 'থেকে',
    'expenditure.of': 'এর মধ্যে',
    'expenditure.results': 'ফলাফল',
    'expenditure.addExpenditure': 'ব্যয় যোগ করুন',
    'expenditure.addNewExpenditure': 'নতুন ব্যয় যোগ করুন',
    'expenditure.addNewExpenditureDesc': 'বিবরণ এবং সংযুক্তি সহ একটি নতুন ব্যয় রেকর্ড করুন',
    'expenditure.selectDoctor': 'ডাক্তার নির্বাচন করুন',
    'expenditure.selectChamber': 'চেম্বার নির্বাচন করুন',
    'expenditure.selectDoctorFirst': 'প্রথমে ডাক্তার নির্বাচন করুন',
    'expenditure.expenditureDetailsPlaceholder': 'ব্যয়ের বিবরণ লিখুন...',
    'expenditure.amountPlaceholder': 'টাকার পরিমাণ লিখুন (যেমন, ৫০০০.০০)',
    'expenditure.attachment': 'সংযুক্তি',
    'expenditure.attachments': 'সংযুক্তিসমূহ',
    'expenditure.attachmentHelper': 'গ্রহণযোগ্য ফরম্যাট: JPG, PNG, JPEG, PDF (সর্বোচ্চ ১০MB)',
    'expenditure.chooseFiles': 'ফাইল নির্বাচন করুন',
    'expenditure.chooseFile': 'ফাইল নির্বাচন করুন',
    'expenditure.noFileChosen': 'কোন ফাইল নির্বাচিত নয়',
    'expenditure.filesSelected': 'ফাইল নির্বাচিত',
    'expenditure.fileSelected': 'ফাইল নির্বাচিত',
    'expenditure.dragDropFiles': 'ফাইল এখানে টেনে আনুন বা ব্রাউজ করতে ক্লিক করুন',
    'expenditure.addMoreFiles': 'আরো ফাইল যোগ করুন',
    'expenditure.multipleFilesTip': 'আপনি একসাথে একাধিক ফাইল নির্বাচন করতে পারেন বা আবার ক্লিক করে আরো ফাইল যোগ করতে পারেন',
    'expenditure.preview': 'প্রিভিউ',
    'expenditure.selectedFile': 'নির্বাচিত ফাইল',
    'expenditure.selectedFiles': 'নির্বাচিত ফাইলসমূহ',
    'expenditure.uploadedFiles': 'আপলোড করা ফাইলসমূহ',
    'expenditure.remove': 'সরান',
    'expenditure.expenditureAdded': 'ব্যয় যোগ করা হয়েছে',
    'expenditure.expenditureAddedDesc': 'নতুন ব্যয় সফলভাবে রেকর্ড করা হয়েছে',
    'expenditure.noExpenditures': 'কোন ব্যয় পাওয়া যায়নি',
    'expenditure.doctorRequired': 'ডাক্তার নির্বাচন প্রয়োজন',
    'expenditure.chamberRequired': 'চেম্বার নির্বাচন প্রয়োজন',
    'expenditure.expenditureDetailsRequired': 'ব্যয়ের বিবরণ প্রয়োজন',
    'expenditure.amountRequired': 'টাকার পরিমাণ প্রয়োজন',
    'expenditure.attachmentRequired': 'সংযুক্তি প্রয়োজন',
    'expenditure.invalidAmount': 'অনুগ্রহ করে একটি বৈধ টাকার পরিমাণ লিখুন',
    'expenditure.filterByChamber': 'চেম্বার দিয়ে ফিল্টার',
    'expenditure.allChambers': 'সকল চেম্বার',
    
    // Deposit
    'deposit.title': 'জমা ব্যবস্থাপনা',
    'deposit.subtitle': 'চেম্বারের জমা এবং আর্থিক রেকর্ড পরিচালনা করুন',
    'deposit.search': 'জমা খুঁজুন...',
    'deposit.searchPlaceholder': 'ডাক্তার, চেম্বার, অ্যাকাউন্ট বা টাকার পরিমাণ দিয়ে খুঁজুন',
    'deposit.doctorName': 'ডাক্তারের নাম',
    'deposit.chamberName': 'চেম্বারের নাম',
    'deposit.account': 'অ্যাকাউন্ট',
    'deposit.amount': 'টাকার পরিমাণ',
    'deposit.status': 'অবস্থা',
    'deposit.actions': 'কার্যক্রম',
    'deposit.edit': 'সম্পাদনা',
    'deposit.view': 'দেখুন',
    'deposit.download': 'ডাউনলোড',
    'deposit.active': 'সক্রিয়',
    'deposit.inactive': 'নিষ্ক্রিয়',
    'deposit.previous': 'পূর্ববর্তী',
    'deposit.next': 'পরবর্তী',
    'deposit.showing': 'দেখানো হচ্ছে',
    'deposit.to': 'থেকে',
    'deposit.of': 'এর মধ্যে',
    'deposit.results': 'ফলাফল',
    'deposit.addDeposit': 'জমা যোগ করুন',
    'deposit.addNewDeposit': 'নতুন জমা যোগ করুন',
    'deposit.addNewDepositDesc': 'বিবরণ এবং সংযুক্তি সহ একটি নতুন জমা রেকর্ড করুন',
    'deposit.selectDoctor': 'ডাক্তার নির্বাচন করুন',
    'deposit.selectChamber': 'চেম্বার নির্বাচন করুন',
    'deposit.selectAccount': 'অ্যাকাউন্ট নির্বাচন করুন',
    'deposit.selectDoctorFirst': 'প্রথমে ডাক্তার নির্বাচন করুন',
    'deposit.amountPlaceholder': 'টাকার পরিমাণ লিখুন (যেমন, ৫০০০.০০)',
    'deposit.attachment': 'সংযুক্তি',
    'deposit.attachments': 'সংযুক্তিসমূহ',
    'deposit.attachmentHelper': 'গ্রহণযোগ্য ফরম্যাট: JPG, PNG, JPEG, PDF (সর্বোচ্চ ১০MB)',
    'deposit.chooseFiles': 'ফাইল নির্বাচন করুন',
    'deposit.chooseFile': 'ফাইল নির্বাচন করুন',
    'deposit.noFileChosen': 'কোন ফাইল নির্বাচিত নয়',
    'deposit.filesSelected': 'ফাইল নির্বাচিত',
    'deposit.fileSelected': 'ফাইল নির্বাচিত',
    'deposit.dragDropFiles': 'ফাইল এখানে টেনে আনুন বা ব্রাউজ করতে ক্লিক করুন',
    'deposit.addMoreFiles': 'আরো ফাইল যোগ করুন',
    'deposit.multipleFilesTip': 'আপনি একসাথে একাধিক ফাইল নির্বাচন করতে পারেন বা আবার ক্লিক করে আরো ফাইল যোগ করতে পারেন',
    'deposit.preview': 'প্রিভিউ',
    'deposit.selectedFile': 'নির্বাচিত ফাইল',
    'deposit.selectedFiles': 'নির্বাচিত ফাইলসমূহ',
    'deposit.uploadedFiles': 'আপলোড করা ফাইলসমূহ',
    'deposit.remove': 'সরান',
    'deposit.depositAdded': 'জমা যোগ করা হয়েছে',
    'deposit.depositAddedDesc': 'নতুন জমা সফলভাবে রেকর্ড করা হয়েছে',
    'deposit.noDeposits': 'কোন জমা পাওয়া যায়নি',
    'deposit.doctorRequired': 'ডাক্তার নির্বাচন প্রয়োজন',
    'deposit.chamberRequired': 'চেম্বার নির্বাচন প্রয়োজন',
    'deposit.accountRequired': 'অ্যাকাউন্ট নির্বাচন প্রয়োজন',
    'deposit.amountRequired': 'টাকার পরিমাণ প্রয়োজন',
    'deposit.attachmentRequired': 'সংযুক্তি প্রয়োজন',
    'deposit.invalidAmount': 'অনুগ্রহ করে একটি বৈধ টাকার পরিমাণ লিখুন',
    'deposit.filterByChamber': 'চেম্বার দিয়ে ফিল্টার',
    'deposit.allChambers': 'সকল চেম্বার',
    
    // Account
    'account.title': 'ব্যাংক অ্যাকাউন্ট ব্যবস্থাপনা',
    'account.subtitle': 'ব্যাংক অ্যাকাউন্ট এবং আর্থিক তথ্য পরিচালনা করুন',
    'account.search': 'অ্যাকাউন্ট খুঁজুন...',
    'account.searchPlaceholder': 'ডাক্তার, অ্যাকাউন্ট টাইপ, প্রতিষ্ঠান বা অ্যাকাউন্ট নম্বর দিয়ে খুঁজুন',
    'account.doctorName': 'ডাক্তারের নাম',
    'account.accountType': 'অ্যাকাউন্ট টাইপ',
    'account.accountOrganization': 'অ্যাকাউন্ট প্রতিষ্ঠান',
    'account.accountNumber': 'অ্যাকাউন্ট নম্বর',
    'account.status': 'অবস্থা',
    'account.actions': 'কার্যক্রম',
    'account.edit': 'সম্পাদনা',
    'account.view': 'দেখুন',
    'account.active': 'সক্রিয়',
    'account.inactive': 'নিষ্ক্রিয়',
    'account.previous': 'পূর্ববর্তী',
    'account.next': 'পরবর্তী',
    'account.showing': 'দেখানো হচ্ছে',
    'account.to': 'থেকে',
    'account.of': 'এর মধ্যে',
    'account.results': 'ফলাফল',
    'account.addAccount': 'অ্যাকাউন্ট যোগ করুন',
    'account.addNewAccount': 'নতুন অ্যাকাউন্ট যোগ করুন',
    'account.addNewAccountDesc': 'বিবরণ এবং তথ্য সহ একটি নতুন অ্যাকাউন্ট যোগ করুন',
    'account.selectDoctor': 'ডাক্তার নির্বাচন করুন',
    'account.selectAccountType': 'অ্যাকাউন্ট টাইপ নির্বাচন করুন',
    'account.selectDoctorFirst': 'প্রথমে ডাক্তার নির্বাচন করুন',
    'account.accountOrganizationPlaceholder': 'যেমন, বিকাশ, ব্র্যাক ব্যাংক, ইসলামী ব্যাংক',
    'account.accountNumberPlaceholder': 'অ্যাকাউন্ট নম্বর লিখুন',
    'account.accountAdded': 'অ্যাকাউন্ট যোগ করা হয়েছে',
    'account.accountAddedDesc': 'নতুন অ্যাকাউন্ট সফলভাবে যোগ করা হয়েছে',
    'account.noAccounts': 'কোন অ্যাকাউন্ট পাওয়া যায়নি',
    'account.doctorRequired': 'ডাক্তার নির্বাচন প্রয়োজন',
    'account.accountTypeRequired': 'অ্যাকাউন্ট টাইপ নির্বাচন প্রয়োজন',
    'account.accountOrganizationRequired': 'অ্যাকাউন্ট প্রতিষ্ঠান প্রয়োজন',
    'account.accountNumberRequired': 'অ্যাকাউন্ট নম্বর প্রয়োজন',
    'account.invalidAccountNumber': 'অনুগ্রহ করে একটি বৈধ অ্যাকাউন্ট নম্বর লিখুন',
    'account.mfs': 'মোবাইল ব্যাংকিং',
    'account.bank': 'ব্যাংক',
    'account.mfsFormatHint': 'ফরম্যাট: ০১XXXXXXXX (১১ ডিজিট, তৃতীয় ডিজিট অবশ্যই ৩-৯ হতে হবে)',
    'account.bankFormatHint': 'ফরম্যাট: ৮-১৮ ডিজিট ব্যাংক অ্যাকাউন্ট নম্বর',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Helper to detect client-side rendering
const isClient = typeof window !== 'undefined'

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  // Add a state to track if we've mounted to avoid hydration mismatch
  const [mounted, setMounted] = useState(false)
  
  // Use a state initialization function to check localStorage synchronously at first render
  const [language, setLanguage] = useState<Language>(() => {
    // Only access localStorage on the client-side
    if (isClient) {
      const savedLanguage = localStorage.getItem('docledger-language') as Language
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'bn')) {
        return savedLanguage
      }
    }
    return 'en'
  })

  // Mark component as mounted after first render
  useEffect(() => {
    setMounted(true)
  }, [])
  
  // This useEffect is kept to handle any changes to localStorage that might happen outside this component
  useEffect(() => {
    const savedLanguage = localStorage.getItem('docledger-language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'bn') && savedLanguage !== language) {
      setLanguage(savedLanguage)
    }
  }, [language])

  // Save language preference to localStorage when it changes
  const handleLanguageChange = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('docledger-language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key
  }

  const formatNumber = (num: number): string => {
    const formattedNum = num.toLocaleString()
    return language === 'bn' ? englishToBengaliNumbers(formattedNum) : formattedNum
  }

  const formatCurrency = (amount: number): string => {
    const formatted = new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'BDT',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(amount).replace('BDT', '৳')
    
    return language === 'bn' ? englishToBengaliNumbers(formatted) : formatted
  }

  const formatDate = (date: Date, format: string = 'MMMM d, yyyy'): string => {
    if (language === 'bn') {
      const day = englishToBengaliNumbers(date.getDate().toString())
      const month = bengaliMonths[date.getMonth()]
      const year = englishToBengaliNumbers(date.getFullYear().toString())
      
      if (format === 'MMMM d, yyyy') {
        return `${month} ${day}, ${year}`
      }
      if (format === 'MMM d, yyyy') {
        // For abbreviated month format like "Sep 10, 2025"
        return `${bengaliMonths[date.getMonth()]} ${day}, ${year}`
      }
      // Add more format options as needed
      return `${day}/${englishToBengaliNumbers((date.getMonth() + 1).toString())}/${year}`
    }
    
    // For English, use dynamic import to avoid SSR issues
    if (typeof window !== 'undefined') {
      return formatDateFn(date, format)
    }
    
    // Fallback for SSR
    return date.toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    })
  }

  const value = {
    language,
    setLanguage: handleLanguageChange,
    t,
    formatNumber,
    formatCurrency,
    formatDate
  }

  // If we haven't mounted yet, return a div with the same className structure but no content
  // to avoid flickering. We could also return null, but that might cause layout shifts.
  if (!mounted && isClient) {
    return (
      <div className="font-sans">
        {/* Empty div with the same structure to prevent layout shift */}
      </div>
    )
  }
  
  return (
    <LanguageContext.Provider value={value}>
      <div className={language === 'bn' ? 'font-bengali' : 'font-sans'}>
        {children}
      </div>
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
